-- schema.sql
-- PostgreSQL DDL for the Supabase Publishers database

CREATE TABLE IF NOT EXISTS public.publishers (
  "PUB_ID" VARCHAR PRIMARY KEY,
  "PUB_NAME" VARCHAR,
  "CITY" VARCHAR,
  "STATE" VARCHAR
);

CREATE TABLE IF NOT EXISTS public.authors (
  "AU_ID" VARCHAR PRIMARY KEY,
  "AU_LNAME" VARCHAR NOT NULL,
  "AU_FNAME" VARCHAR NOT NULL,
  "PHONE" VARCHAR,
  "ADDRESS" VARCHAR,
  "CITY" VARCHAR,
  "STATE" VARCHAR,
  "COUNTRY" VARCHAR,
  "POSTALCODE" VARCHAR
);

CREATE TABLE IF NOT EXISTS public.titles (
  "TITLE_ID" VARCHAR PRIMARY KEY,
  "TITLE" VARCHAR NOT NULL,
  "TYPE" VARCHAR NOT NULL,
  "PUB_ID" VARCHAR,
  "PRICE" NUMERIC,
  "ADVANCE" NUMERIC,
  "TOTAL_SALES" NUMERIC,
  "NOTES" VARCHAR,
  "PUBDATE" DATE NOT NULL,
  "CONTRACT" NUMERIC,
  CONSTRAINT fk_titles_publishers
    FOREIGN KEY ("PUB_ID") REFERENCES public.publishers("PUB_ID")
);

CREATE TABLE IF NOT EXISTS public.stores (
  "STOR_ID" VARCHAR PRIMARY KEY,
  "STOR_NAME" VARCHAR,
  "STOR_ADDRESS" VARCHAR,
  "CITY" VARCHAR,
  "STATE" VARCHAR,
  "COUNTRY" VARCHAR,
  "POSTALCODE" VARCHAR,
  "PAYTERMS" VARCHAR
);

CREATE TABLE IF NOT EXISTS public.sales (
  "STOR_ID" VARCHAR,
  "ORD_NUM" VARCHAR,
  "SDATE" DATE,
  PRIMARY KEY ("STOR_ID", "ORD_NUM"),
  CONSTRAINT fk_sales_stores
    FOREIGN KEY ("STOR_ID") REFERENCES public.stores("STOR_ID")
);
